name: Build & publish to npm

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version: 18

      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm install

      - name: Crawl balance data
        run: pnpm crawl

      - name: Build package
        run: pnpm build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: balance-buff-viewer.js
          body: |
            Download **balance-buff-viewer.js** and put it in your plugins folder.
            If you already have one, it will automatically update-to-date.
